sudo: required
dist: trusty
language: php
php:
  - "7.1"
  - "7.2"

services:
  - docker

install:
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - cat Dockerfile
  - docker-compose build --build-arg PHP_VERSION=${TRAVIS_PHP_VERSION}

script:
  - docker-compose run tests composer install --prefer-source --no-interaction && php ./vendor/bin/phpunit --coverage-clover ./clover.xml

after_script:
  - docker-compose run tests php ./vendor/bin/php-coveralls -v
